# Generated by Django 4.0.4 on 2022-04-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='telefone',
        ),
    ]
